### ISSUE TITLE
create two of the same type pages, the data are binded together (Angular,React)

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#731] opened 2019-06-13 21:55 UTC
How to reproduce (in Angular and React):
1. create a two list pages
2. start the project
3. add an entry in first list page 
4. then redirect to the second list page, you will see the entry you added for 1st page also showed in the second list page

**Comment by streetcoder123** [comment] 2019-06-13 22:51
What do you mean by `redirect`? Does it mean just go to the url for second list page through the url or navigation link in the navbar?

**Comment by SahilTara** [comment] 2019-06-14 00:32
Yeah this was actually something we discussed. We weren't really sure if users would want more complex templates (filled with more code), or if they would want simpler templates which had shared data between the types.  We went with providing the user simplicity but if you feel that we should have serperate bindings for the pages, go for it since I can see good arguments for both sides.

**Comment by xtinah-w** [comment] 2019-07-12 02:03
This is the expected behaviour from the current design rather than a bug, thus, closing this issue.

**Closed as completed by xtinah-w** 2019-07-12 02:03 UTC
