### ISSUE TITLE
Incorrect Deployment Status After Signing Out command palette

### ISSUE THREAD

**Issue by trevorNgo** [microsoft/WebTemplateStudio#427] opened 2019-04-12 18:27 UTC
Running the sign out command before generation does not show failed deploy status in postgen modal.

**Comment by Tanya0609** [comment] 2019-08-08 18:06
I tried to reproduce this bug. This bug has been prevented with new features added in the wizard.

1. when user tried to sign out anything, a popup will show up to confirm their action. Then added Azure services will be automatically removed.
2. when user is in post generation modal, anywhere outside of the modal is not clickable, so user won't be able to sign out at this stage.

thus, close this issue

**Comment by SahilTara** [comment] 2019-08-08 22:14
@Tanya0609 so running the azure signout command within the command pallet updates the users signin status in the wizard? (Ctrl shift p) I dont think this issue is fixed its OOS though since its up to vscode to expose the API

**Comment by sibille** [comment] 2019-11-04 14:35
@SahilTara, this is fixed as the status in the wizard is updated and any services that need azure login are removed. 

Verified in version: 
Templates version: 0.0.19298.1
Wizard version: 0.0.1929801

**Closed by sibille** 2019-11-04 14:35 UTC
Labels: Extension, Wizard, bug
