### ISSUE TITLE
Unable to start new project

### ISSUE THREAD

**Issue by epakconsultant** [Microsoft/WebTemplateStudio#744] opened 2019-06-17 02:00 UTC
Repro steps:

1.
2.

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1915901
OS: win32
VS Code Version: 1.35.0

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (C:/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1915901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (C:/Users/AGA/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1915901/out/launchExperience.js:4:58)
```

</details>

**Comment by smmatte** [comment] 2019-06-19 17:54
Hello, could you provide us with more details and how to reproduce this? Thank you so much for your help.

**Comment by epakconsultant** [comment] 2019-06-19 18:37
On Wednesday, 19 June 2019, 22:54:04 GMT+5, smmatte <notifications@github.com> wrote:  
 
 
Hello, could you provide us with more details and how to reproduce this? Thank you so much for your help.

**Comment by Tanya0609** [comment] 2019-07-02 19:05
Hi @epakconsultant, we could not reproduce this bug in all our test windows machines. Since we have done two release after you reported this bug. It includes more features too. Would you mind re-downloading the extension from the marketplace and see if "the unable to start bug" is gone or not?

**Comment by Tanya0609** [comment] 2019-07-31 17:57
Hi @epakconsultant, the solution to issues related to this one has been merged into our code base, and will be released next Monday. Please download the new release extension from marketplace or update your current extension, and the issue should be fixed for you. Thus, we will close this issue.

If the issue still exists, please let us know! Thank you so much for your feedback!

**Closed as completed** 2019-07-31 17:58 UTC
Labels: bug, Can not reproduce
