### ISSUE TITLE
Request to get master detail text failed: Error: Request Header Fields Too Large

### ISSUE THREAD

**Issue by dea398** [Microsoft/WebTemplateStudio#1270] opened 2019-12-09 18:04 UTC
Hi, I created a vue app with flask as a backend. I choose the master detail template and grid template but they are throwing this error:

Request to get master detail text failed: Error: Request Header Fields Too Large

If I run this website (I uploaded) to azure it is working properly. Why is not working in my local pc?

This is the version of my vs code in a windows 10 O.S

![image](https://user-images.githubusercontent.com/11136878/70460465-62929400-1a84-11ea-8c79-9fc1f9a1cf7e.png)

**Comment by sibille** [comment] 2019-12-12 08:09
Thanks for reporting @dea398. 
Both pages should work fine locally as well as on the server. What version of Python are you using?

**Comment by sibille** [comment] 2020-10-29 11:52
Closing this as we're not able to reproduced. Please reopen with more details if this is still an issue

**Closed as completed by sibille** 2020-10-29 11:52 UTC
Labels: bug, Can not reproduce
