### ISSUE TITLE
can't launch

### ISSUE THREAD

**Issue by hudyyy** [Microsoft/WebTemplateStudio#767] opened 2019-06-20 06:25 UTC
Repro steps:

1.install 
2.command+shift+p , Web Template Studio: Launch

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1915901
OS: darwin
VS Code Version: 1.35.1

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1915901/out/launchExperience.js:40:23)
Generator.next (<anonymous>)
fulfilled (/Users/huangqingyu/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1915901/out/launchExperience.js:4:58)
```

</details>

**Comment by Tanya0609** [comment] 2019-06-20 16:35
Hi, @hudyyy, thank you for reporting this issue! We will take a look at it and get back to you soon.

**Comment by jasmingoh** [comment] 2019-07-04 18:43
Hi @hudyyy, I'm one of the developer working on the extension. We are aware of this issue, but unfortunately, we are not able to reproduce it. It would be awesome if you can provide us with more details about what you did to run into that error.

We have a new version of the extension up on VS Code market place now, 0.0.1918291. Please re-launch the extension and let us know if you're still encountering the problem.

**Comment by SahilTara** [comment] 2019-07-05 23:17
@jasmingoh Have you tried provisioning a vm with low resources (4gb ram limit). Have you tried trying it on a computer with lower specs (since the garage laptops are very nice).

**Comment by jasmingoh** [comment] 2019-07-08 21:23
@SahilTara I'm able to reproduce it now using one of our mac

**Comment by jasmingoh** [comment] 2019-07-08 21:24
@hudyyy We have a solution in mind now, and we are working on it. Will let you know when there's update.
ADO task: https://microsoftgarage.visualstudio.com/Intern%20GitHub/_sprints/taskboard/WTS%20Team/Intern%20GitHub/Y19-VS/08

**Comment by SahilTara** [comment] 2019-07-09 00:18
@jasmingoh only people with access to your sprint board can see that link.

**Comment by vvatkov** [comment] 2019-07-16 10:49
@jasmingoh I receive that error message when I launch the extension on Windows. The extension, however, is built on my Windows development environment using the provided **createVsix** installation script.

**Comment by Tanya0609** [comment] 2019-07-31 17:56
Hi @vvatkov, @hudyyy, the solution to this issue has been merged into our code base, and will be released next Monday. Please download the new release extension from marketplace or update your current extension, and the issue should be fixed for you. 

If the issue still exists, please let us know! Thank you so much for your feedback!

**Comment by streetcoder123** [comment] 2019-07-31 19:55
@Tanya0609 Should we close this issue?

**Comment by vvatkov** [comment] 2019-08-01 08:40
> @Tanya0609 Should we close this issue?

Thank you!

I found that there was a mismatch between the SHA256 hash of the Web.Any.Templates.mstx and the one that the CoreTemplateStudio API expects. So the problem on my side was an integrity check error. Now it's OK.

**Comment by Tanya0609** [comment] 2019-08-02 20:37
@vvatkov Glad to hear the problem is solved for you!

The PR should solve the problem in your local @vvatkov 
Please let us know if you have further question :)

I will close this issue for now.

**Closed as completed by Tanya0609** 2019-08-02 20:37 UTC
Labels: bug

**Comment by hudyyy** [comment] 2019-08-19 01:28
Thank you for solve this problem，and so sorry for no reply,  Because im so busy these few months:)
