### ISSUE TITLE
The extension does not work in "remote containers"

### ISSUE THREAD

**Issue by sesameguy** [Microsoft/WebTemplateStudio#1421] opened 2020-04-17 08:06 UTC
while using "**remote containers**" & Select "**Web Template Studio: Launch**"

the below message is shown:
``
Cannot read property 'objectMode' of undefined
``

**Comment by sibille** [comment] 2020-04-20 08:47
@sesameguy, thanks for reporting!

**Comment by sibille** [comment] 2020-07-30 07:00
@sesameguy, can you still reproduce this error?
I've seen this message before, but can no longer reproduce on remote containers nor on VS Codespaces.
If you can still reproduce, could you provide detailed repro steps?

**Comment by sibille** [comment] 2020-10-22 10:04
Closing this as I tested again with nightly version: 

Templates version: 0.3.20296.1
Wizard version: 0.3.2029601

and could not reproduce. 
Please reopen if this is still an issue.

**Closed as completed by sibille** 2020-10-22 10:04 UTC
Labels: bug
