### ISSUE TITLE
Angular Feedback (New)

### ISSUE THREAD

**Issue by Tanya0609** [Microsoft/WebTemplateStudio#1123] opened 2019-08-21 18:26 UTC
## Angular Feedback from John Papa 
Although the comments are documented based on each file, it apply to the entire generated project

### one liner / remove unnecessary comments and lines
- [x] Warning-message.module.ts: Make the arrays all one liners (smaller is better) 
- [x] Removing extra lines makes generated code smaller (usually people like this) 
- [ ] Master-detail.service.ts: @Injectable({}) should be one line 
- [x] App.module.ts: Empty arrays, objects should be removed  
- [x] App.component.html: Remove comments, no extra stuff is necessary 
                   - Every comment should be intentional and tell something really important 
                   - If the comment wasn't there, would it still make sense? 
- [x] app-routing.module.ts: remove empty objects from NgModule 
                  - When you generate pages, it might be nice to have a home page 

### code styles
- [x] Newer ones do not use do providers array, should be moved to service 
- [x] change mod to m or module
- [x] function or variable names should be camel case i.e. master-detail.component.ts
- [x] Interface should have its own file 

### add error handling
- [x] Add in error handling (e.g. this.http.get should have a catch) 

### environments
- [x] environments: add a comment to both prod and dev file to explain the difference between the two

**Comment by Tanya0609** [comment] 2019-08-21 18:27
## Server related code

- [  ] BuildScript.js 
- Put a comment at the top explaining what this script is for 
- People may be confused why angular-cli is not being used 

-[ ] Package.json
- Don't use nodemon, you don't want that to go to production 
- Take out nodemon completely and just use node 
- Right now nodemon is a devDependencies, this may break things when it's deployed

**Comment by Tanya0609** [comment] 2019-08-21 18:27
### Accessibility 
- [x] Accessibility standards for Angular code should be considered (for example, alt text on images, aria role) 

### CSS
- [x] If necessary, clean up app.component.css. The CSS here will be inherited by all the children.
- [ ] double check the way we import svgs, is it the way to import svgs in css? If not, then fix it.

**Comment by Tanya0609** [comment] 2019-08-21 18:27
- [  ] Environments 
- Add a comment to both prod and dev file to explain the difference between the two 

- [  ] Main.ts 
- Looks good 😊 
- Consider looking into progressive apps (PWA)

**Comment by Tanya0609** [comment] 2019-08-21 18:29
Although the comments are documented based on each file, it applys to the entire generated project

**Comment by mcmxcdev** [comment] 2019-08-26 06:29
@Tanya0609, I would like to work on this, since I have a couple years experience with Angular and worked with Angular 2-8 and know a thing or two about best practices ;)

The issue is very big though, imo it should be split up into multiple issues? At least PWA, http interceptors, authentication

**Comment by traore-i** [comment] 2019-08-26 12:45
@mhatvan I agree with potentially splitting this issue. May make things easier when cross-referencing PRs to a specific part of the feedback

**Comment by Tanya0609** [comment] 2019-08-28 17:22
> @Tanya0609, I would like to work on this, since I have a couple years experience with Angular and worked with Angular 2-8 and know a thing or two about best practices ;)
> 
> The issue is very big though, imo it should be split up into multiple issues? At least PWA, http interceptors, authentication

Hi @mhatvan, thank you for helping out with contributing 👍The reason why this issue is big is that we used it as a placeholder of all the feedback we got from John and we weren't sure if we have capacity to work on it or not. Agree with you, we can split them into PWA, http interceptors, authentication and the basics. 

Also, we already have issues for authentication and PWA, it applies to all the frameworks we have, so I just move those portion of feedback over.

**Comment by mcmxcdev** [comment] 2019-08-29 23:23
@Tanya0609 Good to hear!

**Feedback regarding the leftover checkboxes:**

*CSS:*
* `app.component.css` lgtm
* I don't see any svgs imported in css?

*a11y:*
* There could be some additional codelyzer rules added to `tslint.json`
https://web.dev/accessible-angular-with-codelyzer/

*various:*
* I would need more information/mockups regarding having a home page generated, if that is a requirement.
* @Injectable being a two-liner looks ok to me, that's also how I found it in the angular style guide itself

*Some other isues that I found while working on the project:*
- tslint and prettier not working in `/AngularDefault/src/app/app-shell` folder
- folder is called `/AngularJS` which can be confusing since it is the naming convention for Angular 1
- bootstrap is missing jquery and popperjs dependencies (for modal/tooltip functionality)
- a lot of unsolved tslint issues

**Comment by mcmxcdev** [comment] 2019-09-11 18:10
Any updates from your side regarding my feedback, @Tanya0609 ?

If not then I would remove the WIP from https://github.com/microsoft/WebTemplateStudio/pull/1157 and we could get it merged, it has a lot of changed files already anyways.

**Comment by sibille** [comment] 2019-09-23 17:06
Sorry for the delay @mhatvan, we're currently reorganizing the team. You can remove the WIP and we'll have a look at your PR asap.

**Comment by sibille** [comment] 2019-10-25 11:55
Opened issues #1215 and #1216 to track the remaining work

**Closed as completed by sibille** 2019-10-25 11:55 UTC
Labels: enhancement, code-style, Generated Code
